import React from "react";
import { useReach, useClasses } from "../../hooks";
import styles from "../../styles/Global.module.css";
import terms from "../../styles/Terms.module.css";

const Terms = () => {
    const { termsAccepted, termsRejected } = useReach();

    return (
        <div className={ useClasses(
            styles.subContainer,
            terms.container,
        ) }>
            <div className={ useClasses(
                terms.titleBox,
            ) }>
                <div className={ useClasses(
                    terms.innerTitleBox,
                ) }>
                    <h2 className={ useClasses(
                        terms.title
                    ) }>Terms<br />and<br />Conditions</h2>
                </div>
            </div>
            <div className={ useClasses(
                terms.termsBox,
            ) }>
                <div className={ useClasses(
                    terms.innerTermsBox,
                ) }>
                    <p className={ useClasses(
                        terms.terms
                    ) }>
                        This DApp is solely for the purpose of fundraising.
                        Your continued use means that you agree to the following terms and conditions:
                        <br />
                        1. Tickets' price is set by the Deployer. <br />
                        2. The deadline is set by the Deployer. <br />
                        3. After the deadline elapses and the tickets haven't been sold out, the original price, whatever it may be will increased by 25%. <br />
                        4. The winner only gets 50% of all revenue generated from the tickets purchased. <br />
                        5. 50% of the proceedings goes to the Deployer. <br />
                        6. After tickets have been purchased you will be provided with a ticket number generated by the contract, this cannot be changed. <br />
                    </p>
                </div>
            </div>
            <div className={ useClasses(
                terms.choiceBox
            ) }>
                <button className={ useClasses(
                    terms.choices,
                    terms.positive,
                ) } onClick={ termsAccepted }>Accept</button>
                <button className={ useClasses(
                    terms.choices,
                    terms.negative,
                ) } onClick={ termsRejected }>Reject</button>
            </div>
        </div>
    );
};

export default Terms;